from typing import Optional, TypedDict, Callable

class LoggerOptions(TypedDict, total=False):
    level: int  # Logging level (e.g., logging.INFO, logging.DEBUG)
    format: str  # Log message format
    datefmt: str  # Date format in log messages

class MetricsOptions(TypedDict, total=False):
    enabled: bool
    history_limit: int  # How many requests to keep in memory for metrics
    refresh_interval: float  # Dashboard refresh interval in seconds

class AuthOptions(TypedDict, total=False):
    auth_enabled: bool
    username: str
    password: str
    username_env: str
    password_env: str
    auth_fn: Callable[[str, str], bool]

class ApiOptions(TypedDict, total=False):
    api_enabled: bool
    api_key: str
    api_key_env: str
    api_auth_fn: Callable[[str], bool]

class SupertracerOptions(TypedDict, total=False):
    logger_options: LoggerOptions  # Options for configuring the logger
    metrics_options: MetricsOptions # Options for metrics dashboard
    auth_options: AuthOptions # Options for authentication
    save_own_traces: bool  # Whether to save traces generated by Supertracer itself