from typing import Optional, TypedDict

class LoggerOptions(TypedDict, total=False):
    level: int  # Logging level (e.g., logging.INFO, logging.DEBUG)
    format: str  # Log message format
    datefmt: str  # Date format in log messages

class MetricsOptions(TypedDict, total=False):
    enabled: bool
    history_limit: int  # How many requests to keep in memory for metrics
    refresh_interval: float  # Dashboard refresh interval in seconds

class SupertracerOptions(TypedDict, total=False):
    logger_options: LoggerOptions  # Options for configuring the logger
    metrics_options: MetricsOptions # Options for metrics dashboard
    save_own_traces: bool  # Whether to save traces generated by Supertracer itself